/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Remote.Attendance.Monitoring.System;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
